version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/backendali
    overwrite: true
permissions:
  - object: /home/ubuntu/backendali
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: ubuntu
